name: Build Image
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

env:
  PKR_VAR_MIRROR: https://mirror.init7.net/opnsense
  PKR_VAR_VERSION: 25.7
  PKR_VAR_ISO_CHECKSUM: sha1:e388904d39e4e9604a89111b8410c98474782a41

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Disable triggers
        run: |
          mkdir -p /etc/dpkg/dpkg.cfg.d
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF

      - name: Set up qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 bridge-utils

      - name: Set up packer
        uses: hashicorp/setup-packer@v3

      - name: Cache ISO image
        uses: actions/cache@v4
        id: cache-iso
        with:
          path: iso
          key: iso-${{ env.PKR_VAR_ISO_CHECKSUM }}

      - name: Get OPNsense ISO
        if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        run: |
          sh get-iso.sh

      - name: Build OPNsense image
        run: |
          packer init .
          packer build .
        env:
          PACKER_LOG: 1
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opnsense-image
          path: output/opnsense.qcow2

  upload-image:
    runs-on: ubuntu-latest
    needs: build-image
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Make sure output directory exists
        run: |
          mkdir -p output

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: opnsense-image
          path: output

      - name: Find all files in repository
        run: |
          find . -type f

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/*
          body: |
            OPNsense image built and ready for download.
